### ISSUE TITLE
맵 내에서 위로 캔버스 모서리에서 위로 이동을 누루면 에러 메시지가 뜸

### ISSUE THREAD

**Issue by llighter** [llighter/acomon#14]
![image](https://cloud.githubusercontent.com/assets/11993431/25036106/c8f5c626-212c-11e7-89da-44a516890bb4.png)

관용이 형 파일 옮겨서 해보고 있는데 캔버스 모서리에서 밖으로 이동하려고 하면 메시지가 나는것 같음

**Comment by Junghyo** [comment]
@llighter  if절 조건 순서를 바꾸면 해결 되던걸로 기억.
if( map[((charY-64)/64)][(charX/64)]==2 || (charY<=0) ){  을
--> if(  (charY<=0) || map[((charY-64)/64)][(charX/64)]==2 ){

**Comment by llighter** [comment]
@Junghyo 아 그렇네요 ㅋㅋ 앞의 조건이 만족 안되면 뒤에 조건은 검사를 안하니깐 알겠습니다!
