### ISSUE TITLE
index_ver02.html 버그제보.

### ISSUE THREAD

**Issue by moneymashi** [llighter/acomon#19]
![image](https://cloud.githubusercontent.com/assets/26346704/25068082/5c6d5092-2293-11e7-95ad-97c5bf0e4b7f.png)

**Comment by moneymashi** [comment]
https://www.screencast.com/t/4Gw4Ca3lw0V

우리에겐 console.log()라는 좋은기능이 있습니다 :)
@sinew8706 @llighter @Junghyo

**Comment by sinew8706** [comment]
했어!!
