### ISSUE TITLE
맵 화면과 전투화면 구별해서 키 이벤트 발생시키기

### ISSUE THREAD

**Issue by llighter** [llighter/acomon#25]
맵 화면과 전투화면에서 중복사용하는 키(ex. 방향키)에 대해
한 화면이 활성화 되어 있을 때는 다른 화면은 정지되어 있게 하는 방법 구현

@sinew8706 형은 기존 코드 내에서 상태 변수를 가지고 설정하는 방법
@llighter는 이벤트 리스너를 사용하는 방법으로 구현

**Comment by sinew8706** [comment]
기존코드에서 변수값으로 추가완료 다른 상황들은 상황이 추가되면 테스트해봐야함

**Comment by llighter** [comment]
이벤트 리스너를 사용하여 구현하는 방법도 완료됨. 실제 다른 이벤트 발생해서(대화창, 상점) 정상 작동 되는 지 여부는 확인 해 봐야 될 것으로 보임

**Comment by llighter** [comment]
이벤트 발생 확인완료

TODO
 - collision detection 정확하게 하기

**Comment by llighter** [comment]
currentMode 라는 변수를 활용하여 이 값에 따라 맵 이동 모드 ,전투모드, 상점모드를 구분할 수 있어 충돌이 나지 않는다.!
