### ISSUE TITLE
npc생성관련

### ISSUE THREAD

**Issue by sinew8706** [llighter/acomon#26]
npc가 서있는 블럭에는 배경+npc로 이미지가 두번 와야 하기에
크게 본다면 npc만을 그리는 펑션을 만들어야함
우리는 npc수가 적기에 맵 배열에서 npc블럭을 따로 정하고 그 블럭에만 이미지를 두번 불러오면 될듯
@llighter @Junghyo

**Comment by llighter** [comment]
전체 맵을 한번에 로딩하는 방법으로 해결!
