### ISSUE TITLE
2. 간단한 맵 구현하기

### ISSUE THREAD

**Issue by llighter** [llighter/acomon#3]
기본 프로젝트 구성(파일 관리)

* 맵 구현
* 캐릭터 움직임 구현
* 맵의 속성에 따라 갈 수 없는 곳, 갈 수 있는곳 구현(Collision detection)

**Comment by llighter** [comment]
@Junghyo @sinew8706 금요일까지 할 사항 이슈로 열어놨습니다. 확인해주세요 ㅎ

**Comment by sinew8706** [comment]
@llighter 잘봤습니당 @AnyhuEkil

**Comment by Junghyo** [comment]
@llighter 확인확인확확인
