### ISSUE TITLE
로켓단 이번주 토요일까지 미션

### ISSUE THREAD

**Issue by anyhuekil** [llighter/acomon#8]
- 토요일까지 각자 역할에 따른 역할수행
- 역할
  서종원 : 메뉴구현 및 화면구성
  배재현 : 전투 스크립트 구성
@moneymashi 이슈 전송!

**Comment by llighter** [comment]
감시하고 있습니다 ㅎ @AnyhuEkil

**Comment by anyhuekil** [comment]
@llighter 감사까지야^^;;

**Comment by moneymashi** [comment]
@AnyhuEkil @llighter 왜 둘이 대화하는게 내 이메일까지와서 알람켜져야하는가..
ps) 언어유희는 꾸르잼...

**Comment by moneymashi** [comment]
![image](https://cloud.githubusercontent.com/assets/26346704/24967163/2678336e-1fe4-11e7-99c1-285933f1eb26.png)

왜 지메일에서 지멋대로 "감사"를 "감시"라고 적엇을까. @AnyhuEkil @llighter

**Comment by anyhuekil** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 내가 그전에 감시를 감사로 바꾸고 감사까지야를 적었거든 ㅋㅋ

**Comment by sinew8706** [comment]
끝낸거 정리
