### ISSUE TITLE
맵팀에 요구합니다.

### ISSUE THREAD

**Issue by anyhuekil** [llighter/acomon#9]
최소한,
*{margin:0,padding:0}으로 작업해주시길 바랍니다.
하고 안하고에서 어떠한 차이가 날지는 정확히 예상은 불가하나,
현재창 좌표값을 이용한다면 margin,padding값에서 문제가 발생할지도 모른다는 느낌이 들어서...
상대적 좌표(div내 좌표값)으로 작업이 가능하다면 그렇게 해주는게 가장 좋아 보입니다.

추가. 노멀라이즈 초기화에 대해서 어느정도 통일될 필요가 있어보임.
추가. 위 내용과 상반된 말이지만,
이번 프로젝트에 그냥 해보고 어떤 차이가 있는지 직접 확인해보는것도 좋은 방법임.

읽은사람은 확인댓글 !!

@llighter 이리오너라~
@Junghyo 이리오너라~
@moneymashi 이리오너라~
@sinew8706 이리오너라~

**Comment by Junghyo** [comment]
@llighter ㅇㅋ

**Comment by sinew8706** [comment]
우선 캔버스 안에서 문제는 없을 것 같아보임
css부분도 거의 없고 마진패딩0으로 작업하겠음
다만 실전에서는 전체선택자를 지양하는게 좋다고 봐서 추후 페이지등에선 더 토의해봅시다

**Comment by llighter** [comment]
네 저도 관용이형 생각하고 같아요. 일단 맵관련해서는 캔버스 안에서 다 안에 이루어지기때문에 문제 없을 것으로 보입니다. 그외 전체 규칙은 *{margin:0,padding:0} 으로 세팅해서 진행하면 될것 같아요

**Comment by llighter** [comment]
공통적으로 적용된 사안이니 이슈는 닫겠습니다.
